-- MySQL Script generated by MySQL Workbench
-- Fri 30 Sep 2022 11:08:58 AM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_hire_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_hire_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_hire_system` DEFAULT CHARACTER SET utf8 ;
USE `car_hire_system` ;

-- -----------------------------------------------------
-- Table `car_hire_system`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_hire_system`.`bookings` ;

CREATE TABLE IF NOT EXISTS `car_hire_system`.`bookings` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `vehicle_id` INT NULL,
  `date_of_rent` DATE NULL,
  `return_date` DATE NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_bookings_vehicles_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `fk_bookings_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_vehicles`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `car_hire_system`.`vehicles` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `car_hire_system`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_hire_system`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_hire_system`.`customers` ;

CREATE TABLE IF NOT EXISTS `car_hire_system`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(15) NULL,
  `l_name` VARCHAR(15) NULL,
  `ssn` VARCHAR(20) NOT NULL,
  `phone_no` VARCHAR(15) NULL,
  `E_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_hire_system`.`vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_hire_system`.`vehicles` ;

CREATE TABLE IF NOT EXISTS `car_hire_system`.`vehicles` (
  `vehicle_id` INT NOT NULL,
  `category` VARCHAR(11) NOT NULL,
  `board_no` VARCHAR(10) NOT NULL,
  `rent_amount` DECIMAL NULL,
  `color` VARCHAR(10) NULL,
  PRIMARY KEY (`vehicle_id`),
  UNIQUE INDEX `Board_no_UNIQUE` (`board_no` ASC) VISIBLE)
ENGINE = InnoDB;

USE `car_hire_system` ;

-- -----------------------------------------------------
-- Placeholder table for view `car_hire_system`.`today_bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_hire_system`.`today_bookings` (`booking_id` INT, `customer_id` INT, `vehicle_id` INT, `date_of_rent` INT, `return_date` INT);

-- -----------------------------------------------------
-- View `car_hire_system`.`today_bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_hire_system`.`today_bookings`;
DROP VIEW IF EXISTS `car_hire_system`.`today_bookings` ;
USE `car_hire_system`;
CREATE  OR REPLACE VIEW `today_bookings` AS
	select * from bookings where date_of_rent = current_date();

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `car_hire_system`;

DELIMITER $$

USE `car_hire_system`$$
DROP TRIGGER IF EXISTS `car_hire_system`.`bookings_BEFORE_INSERT` $$
USE `car_hire_system`$$
CREATE DEFINER = CURRENT_USER TRIGGER `car_hire_system`.`bookings_BEFORE_INSERT` BEFORE INSERT ON `bookings` FOR EACH ROW
BEGIN
	IF new.date_of_rent > CURDATE()+7 THEN
		SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'customers can only book a vehicle up to 7 days in advance';
	END IF;
    IF new.return_date > new.date_of_rent+7 THEN
		SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = 'customers cannot hire a car for longer than a week';
	END IF;

END$$


USE `car_hire_system`$$
DROP TRIGGER IF EXISTS `car_hire_system`.`bookings_AFTER_INSERT` $$
USE `car_hire_system`$$
$$


DELIMITER ;
